allowBuilds:
  '@scarf/scarf': true
  bcrypt: true
  mongodb-memory-server: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@scarf/scarf'
  - bcrypt
  - mongodb-memory-server
  - unrs-resolver
